### ISSUE TITLE
#[cmdr] does not seem to work when the struct has generic type parameters

### ISSUE THREAD

**Issue by gferon** [mendelt/cmdr#36]
e.g.

```rust
struct MoveScope<T>;

#[cmdr]
impl<T> MoveScope<T> {
...
}
```

I guess we have to start digging now :)

**Comment by mendelt** [comment]
Thank you for reporting this. I'll see if I can fix this in the next release. For now I've added an example for a workaround here: https://github.com/mendelt/cmdr/blob/master/cmdr/examples/04-generic_scope.rs

**Comment by mendelt** [comment]
This should be fixed in 0.3.5
