### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by davidrusu** [mendelt/cmdr#42]
Hi there, was just playing around with this crate and realized the version on crates.io is quite a bit older than what you have on master, seems the API has changed a bit as well.

If it's in a good state, mind publishing a new release?

**Comment by mendelt** [comment]
Thank you for your interest in cmdr. I havent had much time for this project as of late but I should be able to release what I have so far this weekend.

**Comment by mendelt** [comment]
Sorry for not replying sooner, 0.3.12 has been released.
https://crates.io/crates/cmdr
